"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { categories as seedCategories, formatPrice, imageUrl, products as seedProducts, type Product } from "@/lib/products";

export function AccountPanel() {
  const [mode,setMode]=useState<"signin"|"register">("signin"); const [message,setMessage]=useState("");
  function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);const email=String(data.get("email"));localStorage.setItem("gb-demo-account",JSON.stringify({email,name:String(data.get("name")||"")}));setMessage(`Welcome${mode==="register"?" to GB DigiMart":" back"}! Your demo account is ready on this device.`);}
  return <main id="main-content" className="page-shell"><div className="page-heading"><div className="eyebrow" style={{justifyContent:"center"}}><span className="eyebrow-line"/> YOUR GB DIGIMART ACCOUNT</div><h1>A warm <em>welcome.</em></h1></div><form className="auth-card" onSubmit={submit}><h1>{mode==="signin"?"Welcome back":"Join us"}</h1><p>{mode==="signin"?"Sign in to find your favorite things.":"Create an account for a little more goodness."}</p>{mode==="register"&&<><label htmlFor="account-name">Your name</label><input id="account-name" name="name" autoComplete="name" required/></>}<label htmlFor="account-email">Email address</label><input id="account-email" type="email" name="email" autoComplete="email" required/><label htmlFor="account-password">Password</label><input id="account-password" type="password" name="password" autoComplete={mode==="signin"?"current-password":"new-password"} minLength={8} required/><button className="button button-dark" type="submit">{mode==="signin"?"Sign in":"Create account"}<span>→</span></button>{message&&<p role="status">{message}</p>}<p><button type="button" className="text-link" onClick={()=>{setMode(mode==="signin"?"register":"signin");setMessage("")}}>{mode==="signin"?"New here? Create an account":"Already have an account? Sign in"}</button></p><p className="checkout-note">Demo account only: credentials stay on this device and are not securely authenticated.</p></form></main>;
}

type AdminProduct=Omit<Product,"id"> & { id:string; stock:number };
const ADMIN_KEY="gb-demo-products-v1";
export function AdminPanel() {
  const [items,setItems]=useState<AdminProduct[]>([]);const [ready,setReady]=useState(false);const [editing,setEditing]=useState<AdminProduct|null>(null);const [message,setMessage]=useState("");
  useEffect(()=>{try{const saved=localStorage.getItem(ADMIN_KEY);setItems(saved?JSON.parse(saved):seedProducts.map((p)=>({...p,id:String(p.id),stock:p.inStock?10:0})));}catch{setItems(seedProducts.map((p)=>({...p,id:String(p.id),stock:p.inStock?10:0})));}setReady(true);},[]);
  useEffect(()=>{if(ready)localStorage.setItem(ADMIN_KEY,JSON.stringify(items));},[items,ready]);
  function save(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const name=String(form.get("name")).trim();const slug=String(form.get("slug")).trim().toLowerCase().replace(/[^a-z0-9-]+/g,"-");const price=Number(form.get("price"));const stock=Number(form.get("stock"));const category=String(form.get("category"));if(!name||!slug||!Number.isFinite(price)||price<1||!Number.isInteger(stock)||stock<0){setMessage("Please enter a name, valid slug, positive price and stock quantity.");return;}const template=editing??seedProducts[0];const categoryLabel=seedCategories.find((item)=>item.slug===category);const product:AdminProduct={...template,id:editing?.id??slug,slug,name,category,categories:categoryLabel?[categoryLabel]:[],price,regularPrice:price,salePrice:0,minPrice:price,maxPrice:price,stock,inStock:stock>0,rating:editing?.rating??0,reviews:editing?.reviews??0,description:String(form.get("description")||"Made with care in Gilgit-Baltistan."),shortDescription:String(form.get("description")||"Made with care in Gilgit-Baltistan."),weight:String(form.get("weight")||"250 g"),weightOptions:[String(form.get("weight")||"250 g")]};setItems((current)=>editing?current.map((item)=>item.id===editing.id?product:item):[product,...current]);setEditing(null);setMessage(`${name} saved on this device.`);event.currentTarget.reset();}
  if(!ready)return <main id="main-content" className="page-shell"><div className="skeleton"/></main>;
  return <main id="main-content" className="page-shell"><div className="admin-top"><div><div className="eyebrow"><span className="eyebrow-line"/> YOUR SHOP, YOUR WAY</div><h1 style={{fontFamily:"var(--font-display)",fontWeight:400,fontSize:48}}>A little <em>admin.</em></h1><p className="checkout-note">Product edits in this preview are saved only in this browser.</p></div><Link className="text-link" href="/products">View shop ↗</Link></div><form className="admin-form" onSubmit={save}><h2 style={{fontFamily:"var(--font-display)",fontWeight:400,fontSize:25}}>{editing?"Edit this product":"Add a product"}</h2><div className="form-grid"><label>Product name<input name="name" required defaultValue={editing?.name}/></label><label>URL slug<input name="slug" required defaultValue={editing?.slug}/></label><label>Price (PKR)<input name="price" type="number" min="1" required defaultValue={editing?.price}/></label><label>Stock quantity<input name="stock" type="number" min="0" required defaultValue={editing?.stock}/></label><label>Category<select name="category" defaultValue={editing?.category??seedCategories[0].slug}>{seedCategories.map((category)=><option value={category.slug} key={category.slug}>{category.name}</option>)}</select></label><label>Size / weight<input name="weight" defaultValue={editing?.weight??"250 g"}/></label><label className="full-span">Description<input name="description" defaultValue={editing?.description}/></label></div><div style={{display:"flex",gap:10,marginTop:12}}><button className="button button-dark">{editing?"Save changes":"Add product"}<span>→</span></button>{editing&&<button type="button" className="button" onClick={()=>setEditing(null)}>Cancel</button>}</div>{message&&<p role="status" className="checkout-note">{message}</p>}</form><table className="admin-table"><thead><tr><th>Product</th><th>Category</th><th>Price</th><th>Stock</th><th>Manage</th></tr></thead><tbody>{items.map((item)=><tr key={item.id}><td style={{display:"flex",alignItems:"center",gap:9}}><img src={imageUrl(item.image,100)} alt="" width="34" height="38" style={{objectFit:"cover"}}/>{item.name}</td><td>{seedCategories.find((category)=>category.slug===item.category)?.name}</td><td>{formatPrice(item.price)}</td><td>{item.stock}</td><td><div className="admin-actions"><button onClick={()=>{setEditing(item);window.scrollTo({top:0,behavior:"smooth"})}}>Edit</button><button onClick={()=>{setItems((current)=>current.filter((product)=>product.id!==item.id));setMessage(`${item.name} removed from this device.`)}}>Remove</button></div></td></tr>)}</tbody></table></main>;
}
